### ISSUE TITLE
Planifier formation avant fin février

### ISSUE THREAD

**Issue by mrodrigue** [mrodrigue/Drummondville#15]
Service des communications : Sonia, Maxime et nouvelle agente

Loisirs : Marilyn - section événements et cartes (via géomatique)
Arts : Karine - section événements
Greffe : Josée Godin, Marie-Josée Bernier et Suzie d'Anjou - Séances du Conseil et déposer procès verbaux 
Ressources humaines : Cynthia et Mélanie Boutin - Emplois
Ventes-débarras : Marie-ève Pelletier
Règlements : Christiane Blanchette
Blogs : Sébastien Lépine

**Comment by mrodrigue** [comment]
Formation 12 février : Cynthia Quirion, Marilyne Massé, Josée Godin, Marie-Josée Bernier et Marie-Ève Pelletier

Reste : Sébastien Lépine, Karine Labrecque Auclair Mélanie Boutin (p-e Cynthia pourrait lui donner?) Suzie d'Anjou (de retour 78 mars) et Christiane Blanchette (de retour le 29 février)

**Comment by CaroCloutier** [comment]
Mélanie, Karine et Sébastien : formation prévue le 25 février!
